### ISSUE TITLE
Form button styling on docs site

### ISSUE THREAD

**Issue by devalexwhite** [break-stuff/kickstand-ui#114]
There’s an issue with the rendering of the submit button when viewing the Forms section of the docs (https://kickstand-ui.com/components/form.html)

This occurs on Safari for iOS (screen size: iPad 12.9”). 
![IMG_0041](https://user-images.githubusercontent.com/8661998/89414305-2e956e80-d6f8-11ea-8933-a299c5aae3f5.png)

**Comment by break-stuff** [comment]
Release 1.0.3 resolves this issue. Thanks!
