### ISSUE TITLE
Important links on website seem to be dead

### ISSUE THREAD

**Issue by anyway** [break-stuff/kickstand-ui#187]
**Kickstand UI** seems to be a very interesting project... thanks for sharing!

However, I found two dead links on the website: 

Page: [https://kickstand-ui.com/](https://kickstand-ui.com/)
Broken link: [Customize Your Project](https://kickstand-ui.com/design-tokens/design-tokens.html) (button)

Page/Place: [https://kickstand-ui.com/getting-started/installation.html#styles](https://kickstand-ui.com/getting-started/installation.html#styles)
Broken link: [Sass tools](https://kickstand-ui.com/design-tokens/design-tokens.html) (text link)

It seems to be the same page that is not accessible in both cases.

Especially the "some great SASS tools" would interest me.

**Comment by break-stuff** [comment]
Oh, thank you for the heads-up! I will get those fixed right away.

**Comment by lounge4** [comment]
Great, thank you!

I just discovered by accident, the two buttons in the hero element of your home page overlap - under iOS Safari.

But now I leave you alone again ;-)

![IMG_1348](https://user-images.githubusercontent.com/28197256/104843657-0aa39f00-58cc-11eb-9e55-7aab8b142b03.png)

**Comment by anyway** [comment]
Great, thank you!

I just discovered by accident, the two buttons in the hero element of your home page overlap - under iOS Safari.

But now I leave you alone again ;-)

![IMG_1348](https://user-images.githubusercontent.com/28197256/104843657-0aa39f00-58cc-11eb-9e55-7aab8b142b03.png)

**Comment by break-stuff** [comment]
You are awesome! Thank you! I will get that fixed as well.
